In [3]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [4]:
#2. Print the NUMPY version and the configuration.

# Imprimir la versión de NumPy
print("NumPy Version:", np.__version__)

# Imprimir la configuración de NumPy
print("NumPy Configuration:")
print(np.show_config())

NumPy Version: 1.26.3
NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.7",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT

c:\Users\Usuario_1\anaconda3\envs\Ironhack\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [43]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.randint(low=1, high=10, size=(2, 3, 5))

In [44]:
def numpy_info(arr):
    print("\nThe dimension is:", arr.ndim)
    print("The shape is:", arr.shape)
    print("The size is:", arr.size)

In [45]:
print("\nArray Information:")
numpy_info(a)


Array Information:

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [46]:
#4. Print a.
print(a)

[[[5 1 8 5 3]
  [4 3 4 2 8]
  [8 6 2 6 6]]

 [[4 7 7 1 3]
  [6 9 4 8 8]
  [2 7 6 4 5]]]


In [53]:
aa = np.random.random(size=(2, 3, 5))

In [54]:
print(aa)

[[[0.26685016 0.27879111 0.18245207 0.07562868 0.04527398]
  [0.59364765 0.86610526 0.23268953 0.5132233  0.16390551]
  [0.78441446 0.20985756 0.4102484  0.49734253 0.73500104]]

 [[0.16743755 0.50543458 0.93032429 0.04614245 0.49137586]
  [0.96694257 0.72903096 0.03620487 0.37557982 0.30489319]
  [0.28857258 0.42230684 0.95522891 0.58503084 0.39193551]]]


In [55]:
aaa = np.random.randn(2, 3, 5)

In [56]:
print(aaa)

[[[-0.07946357 -1.38272212  1.78178655 -1.87296433 -0.65562714]
  [-0.16696185 -0.50069281 -0.64924217 -0.84274811 -1.08537403]
  [-0.21352912  0.14383979 -0.25903596  1.65094361  0.37115868]]

 [[ 0.23956207 -0.0564549  -1.29645025  1.30171414  0.27548513]
  [ 0.49938218 -0.37224278  1.31500431 -1.95523224  0.23942541]
  [ 3.52871635  0.53975923 -0.96594693  1.2340972  -0.01596865]]]


In [62]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.ones((5, 2, 3))

In [65]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [66]:
# No entendí si pide que los valores sean todos unos o que la suma de ellos sea 1. He hecho todas las posiblidades.

shape = (5, 2, 3)

total_elements = np.prod(shape)

bb = np.ones(shape) / total_elements

print(bb)

[[[0.03333333 0.03333333 0.03333333]
  [0.03333333 0.03333333 0.03333333]]

 [[0.03333333 0.03333333 0.03333333]
  [0.03333333 0.03333333 0.03333333]]

 [[0.03333333 0.03333333 0.03333333]
  [0.03333333 0.03333333 0.03333333]]

 [[0.03333333 0.03333333 0.03333333]
  [0.03333333 0.03333333 0.03333333]]

 [[0.03333333 0.03333333 0.03333333]
  [0.03333333 0.03333333 0.03333333]]]


In [67]:
#7. Do a and b have the same size? How do you prove that in Python code?

print("\nArray Information:")
numpy_info(a)


Array Information:

The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [68]:
print("\nArray Information:")
numpy_info(b)


Array Information:

The dimension is: 3
The shape is: (5, 2, 3)
The size is: 30


In [69]:
a.size == b.size

True

In [70]:
#8. Are you able to add a and b? Why or why not?

sum(a + b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [71]:
# No puedes porque dos arrays no se pueden sumar entre ellos si no tienen la misma forma (shape).

In [72]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.T

In [73]:
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [74]:
numpy_info(c)


The dimension is: 3
The shape is: (3, 2, 5)
The size is: 30


In [75]:
c = np.transpose(b, (1,2,0))

In [87]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [77]:
numpy_info(c)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [78]:
sum(a+c)

array([[11., 10., 17.,  8.,  8.],
       [12., 14., 10., 12., 18.],
       [12., 15., 10., 12., 13.]])

In [79]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = sum(a+c)

In [80]:
d

# Porque ahora tienen la misma shape.

array([[11., 10., 17.,  8.,  8.],
       [12., 14., 10., 12., 18.],
       [12., 15., 10., 12., 13.]])

In [81]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

a

array([[[5, 1, 8, 5, 3],
        [4, 3, 4, 2, 8],
        [8, 6, 2, 6, 6]],

       [[4, 7, 7, 1, 3],
        [6, 9, 4, 8, 8],
        [2, 7, 6, 4, 5]]])

In [82]:
d

array([[11., 10., 17.,  8.,  8.],
       [12., 14., 10., 12., 18.],
       [12., 15., 10., 12., 13.]])

In [83]:
numpy_info(a)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [85]:
numpy_info(c)


The dimension is: 3
The shape is: (2, 3, 5)
The size is: 30


In [86]:
numpy_info(d)


The dimension is: 2
The shape is: (3, 5)
The size is: 15


In [88]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [90]:
print(d.shape)

(3, 5)


In [91]:
d = a + c

In [92]:
d

array([[[ 6.,  2.,  9.,  6.,  4.],
        [ 5.,  4.,  5.,  3.,  9.],
        [ 9.,  7.,  3.,  7.,  7.]],

       [[ 5.,  8.,  8.,  2.,  4.],
        [ 7., 10.,  5.,  9.,  9.],
        [ 3.,  8.,  7.,  5.,  6.]]])

In [ ]:
# La diferencia es que los valores de "d" son floats por la suma de a (int) + c(float).

In [93]:
#12. Multiply a and c. Assign the result to e.

e = a * c

In [94]:
e

array([[[5., 1., 8., 5., 3.],
        [4., 3., 4., 2., 8.],
        [8., 6., 2., 6., 6.]],

       [[4., 7., 7., 1., 3.],
        [6., 9., 4., 8., 8.],
        [2., 7., 6., 4., 5.]]])

In [96]:
#13. Does e equal to a? Why or why not?

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [97]:
type(a) == type(c)

True

In [ ]:
# No son exactamente iguales por tipo porque a es int y e es float, pero a nivel de resultado si lo son porque e es el resultado de multiplicar a por c que c es igual a 1.

In [99]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [100]:
d_max

10.0

In [101]:
d_min

2.0

In [102]:
d_mean

6.066666666666666

In [107]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

In [108]:
f

array([[[5., 1., 8., 5., 3.],
        [4., 3., 4., 2., 8.],
        [8., 6., 2., 6., 6.]],

       [[4., 7., 7., 1., 3.],
        [6., 9., 4., 8., 8.],
        [2., 7., 6., 4., 5.]]])

In [110]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

In [111]:
d

array([[[ 6.,  2.,  9.,  6.,  4.],
        [ 5.,  4.,  5.,  3.,  9.],
        [ 9.,  7.,  3.,  7.,  7.]],

       [[ 5.,  8.,  8.,  2.,  4.],
        [ 7., 10.,  5.,  9.,  9.],
        [ 3.,  8.,  7.,  5.,  6.]]])

In [113]:
mask = np.logical_and(d > d_min, d < d_mean)
f[mask] = 25

In [114]:
f

array([[[25.,  1.,  8., 25., 25.],
        [25., 25., 25., 25.,  8.],
        [ 8.,  6., 25.,  6.,  6.]],

       [[25.,  7.,  7.,  1., 25.],
        [ 6.,  9., 25.,  8.,  8.],
        [25.,  7.,  6., 25., 25.]]])

In [116]:
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
mask = np.logical_and(d < d_max, d > d_mean)
f[mask] = 75


In [117]:
f

array([[[25.,  1., 75., 25., 25.],
        [25., 25., 25., 25., 75.],
        [75., 75., 25., 75., 75.]],

       [[25., 75., 75.,  1., 25.],
        [75.,  9., 25., 75., 75.],
        [25., 75., 75., 25., 25.]]])

In [126]:
#If a value equals to d_mean, assign 50 to the corresponding value in f.
mask = d == d_mean
f[mask] = 50

In [127]:
f

array([[[25.,  0., 75., 25., 25.],
        [25., 25., 25., 25., 75.],
        [75., 75., 25., 75., 75.]],

       [[25., 75., 75.,  0., 25.],
        [75.,  9., 25., 75., 75.],
        [25., 75., 75., 25., 25.]]])

In [128]:
#Assign 0 to the corresponding value(s) in f for d_min in d.
mask = d == d_min
f[mask] = 0

In [125]:
f

array([[[25.,  0., 75., 25., 25.],
        [25., 25., 25., 25., 75.],
        [75., 75., 25., 75., 75.]],

       [[25., 75., 75.,  0., 25.],
        [75.,  9., 25., 75., 75.],
        [25., 75., 75., 25., 25.]]])

In [129]:
#Assign 100 to the corresponding value(s) in f for d_max in d.

mask = d == d_max
f[mask] = 100

In [130]:
f

array([[[ 25.,   0.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.],
        [ 75.,  75.,  25.,  75.,  75.]],

       [[ 25.,  75.,  75.,   0.,  25.],
        [ 75., 100.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  25.]]])

In [132]:
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.

# No tengo el 50. de la media

In [140]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        #[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
       # [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       #[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        #[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        #[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
        #[ 75.,  75.,  25.,  25.,  25.],
        #[ 75.,  25.,  75.,  75.,  75.]],

       #[[ 25.,  25.,  25.,  25., 100.],
        #[ 75.,  75.,  75.,  75.,  75.],
        #[ 25.,  75.,   0.,  75.,  75.]]])

In [134]:
d

array([[[ 6.,  2.,  9.,  6.,  4.],
        [ 5.,  4.,  5.,  3.,  9.],
        [ 9.,  7.,  3.,  7.,  7.]],

       [[ 5.,  8.,  8.,  2.,  4.],
        [ 7., 10.,  5.,  9.,  9.],
        [ 3.,  8.,  7.,  5.,  6.]]])

In [135]:
f

array([[[ 25.,   0.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.],
        [ 75.,  75.,  25.,  75.,  75.]],

       [[ 25.,  75.,  75.,   0.,  25.],
        [ 75., 100.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  25.]]])

In [136]:
#Tengo de resultado otros valores pero entiendo que la mecanica del ejercicio esta bien, solo entender porque no me ha salido del 50 de la media.

In [137]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
        #[ 'D',  'D',  'B',  'B',  'B'],
        #[ 'D',  'B',  'D',  'D',  'D']],

       #[[ 'B',  'B',  'B',  'B',  'E'],
        #[ 'D',  'D',  'D',  'D',  'D'],
        #[ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.

In [142]:
# Definir un diccionario de mapeo
mapping_dict = {0.: "A", 25.: "B", 50.: "C", 75.: "D", 100.: "E"}

# Crear un array de strings utilizando el mapeo
g = np.vectorize(mapping_dict.get)(f)

print(g)

[[['B' 'A' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'A' 'B']
  ['D' 'E' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'B']]]
